### ISSUE TITLE
Can't click next button on setup.

### ISSUE THREAD

**Issue by danielchim** [brianmillar/eXastum#1]
I use easyphp devserver vc9,and i cant even click the next button.

**Comment by brianmillar** [comment]
Hi Daniel, thanks for testing. The project is in prerelease alpha stage and so bugs are expected however I have not seen this issue before, I will look into it. Is it the first Next button in Setup or do you make it through any of the stages before it fails? As a side note, eXastum is designed to work offline using only HTML5, CSS3 and JavaScript, there is no need to run a PHP server, you can if you want but there is no PHP code in the project. Thanks again for the report, I'll look into it.

**Comment by brianmillar** [comment]
Also the Next button will not work on the first page of setup unless you check the checkbox.

**Comment by brianmillar** [comment]
I've removed the checkbox and pushed a commit if that was indeed the issue.

**Comment by danielchim** [comment]
Php server is just the name.The full name is called Easyphp devserver.It usually design as devloping php systems,but i usually using as my daily web server.

**Comment by danielchim** [comment]
Err.....I am a noob.How to close a issue?

**Comment by brianmillar** [comment]
Its ok I'll close it, as a quick note my earlier comment about not needing a localhost server only applies to Firefox, you do need it for Chrome. Hope your problems are resolved now, thanks for testing!
